@baseUrl =  http://localhost:3000
@id_user = 2
@tokenAdopter = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJqb2FvQGdtYWlsLmNvbSIsInJvbGUiOiJhZG9wdGVyIiwiaWF0IjoxNzgyNjEzODgxLCJleHAiOjE3ODI2MTc0ODF9.E6FyoS25VlzGIsWcNgpp2anqlGjLCxKrPJdW5bQL8Lk
@tokenAdm = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJhZG1pbmlzdHJhZG9yM0BnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3ODI2MTM0ODUsImV4cCI6MTc4MjYxNzA4NX0.zmx4gdITS0lqqw5Zr0CaAg4gRF4cHUq92IG6Z5viQKo

### Listar todos os usuários
GET {{baseUrl}}/users
Authorization: Bearer {{tokenAdm}}

### Buscar usuário por ID
GET {{baseUrl}}/users/{{id_user}}
Content-Type: application/json
Authorization: Bearer {{tokenAdm}}

### Adopter logado busca a si mesmo por ID
GET {{baseUrl}}/users/2
Content-Type: application/json
Authorization: Bearer {{tokenAdopter}}

### Atualizar usuário
PUT {{baseUrl}}/users/{{id_user}} 
Content-Type: application/json
Authorization: Bearer {{tokenAdm}}

{
    "name": "carlos",
    "email": "carlos@gmail.com",
    "phone": "549993231312"
}

### Adopter logado atualiza a si mesmo
PUT {{baseUrl}}/users/2
Content-Type: application/json
Authorization: Bearer {{tokenAdopter}}

{
    "name": "João Santos",
    "email": "joaoatualizado@gmail.com",
    "phone": "549993231312"
}

### Atualizar usuário pra admin
PUT {{baseUrl}}/users/{{id_user}} 
Content-Type: application/json
Authorization: Bearer {{tokenAdm}}

{
    "name": "Administrador2",
    "email": "administrador2@gmail.com",
    "phone": "549993231311",
    "role": "admin"
}

### Deletar um usuário
DELETE {{baseUrl}}/users/{{id_user}}
Authorization: Bearer {{tokenAdm}}

###

### TESTE DE ERRO - Listar usuários por id com token de user comum
GET {{baseUrl}}/users
Authorization: Bearer {{tokenAdopter}}

### TESTE DE ERRO - tentando deletar usuário como user comum
DELETE {{baseUrl}}/users/{{id_user}}
Authorization: Bearer {{tokenAdopter}}

### TESTE DE ERRO - TENTAR ATUALIZAÇÃO SEM NENHUM CAMPO NO BODY
PUT {{baseUrl}}/users/2
Content-Type: application/json
Authorization: Bearer {{tokenAdm}}

{
}

###

## TESTE DE ERRO - Buscar usuário inexistente
GET {{baseUrl}}/users/9999
Authorization: Bearer {{tokenAdm}}

### TESTE DE ERRO - Atualizar usuário inexistente
PUT {{baseUrl}}/users/9999
Content-Type: application/json
Authorization: Bearer {{tokenAdm}}

{
    "name": "carlos",
    "email": "carlos@gmail.com",
    "phone": "549993231312"
}

### TESTE DE ERRO - Deletar um usuário inexistente
DELETE {{baseUrl}}/users/9999
Authorization: Bearer {{tokenAdm}}
